name: Docker
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+*'
  schedule:
    # twice a month
    - cron: '20 11 5,20 * *'
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  ndncert:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndncert
