name: Docker
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+*'
  schedule:
    # twice a month
    - cron: '20 11 5,20 * *'
  workflow_dispatch:

permissions:
  attestations: write
  id-token: write
  packages: write

jobs:
  ndncert-build:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndncert-build
      target: build
  ndncert-ca:
    needs: ndncert-build
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndncert-ca
      target: ca
      contexts: build=docker-image://${{ needs.ndncert-build.outputs.image }}
  ndncert-client:
    needs: ndncert-build
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndncert-client
      target: client
      contexts: build=docker-image://${{ needs.ndncert-build.outputs.image }}
